// Consolidated domain types for the user-app

// === Channel Types ===

export interface Channel {
  id: string;
  telegramId: string;
  username: string | null;
  title: string;
  niche: string | null;
  tone: string;
  language: string;
  hashtags: string[];
  // SVG Style Configuration
  svgEnabled: boolean;
  svgStylePrompt: string | null;
  svgThemeColor: string;
  svgTextColor: string;
  svgBackgroundStyle: string;
  svgFontStyle: string;
  // Personal blog settings
  channelMode: string;
  personaName: string | null;
  personaDescription: string | null;
}

// === Persona Types ===

export interface PersonaAsset {
  id: string;
  label: string;
  description: string | null;
  imageUrl: string;
  mimeType: string | null;
  sortOrder: number;
}

export interface StoryArc {
  id: string;
  title: string;
  description: string;
  activeDate: string;
  endDate: string | null;
  isUsed: boolean;
  sortOrder: number;
}

// Minimal channel type for pages that only need basic info
export type ChannelBasic = Pick<Channel, "id" | "title" | "username">;

// === Post Types ===

export type PostStatus =
  | "draft"
  | "scheduled"
  | "publishing"
  | "published"
  | "failed"
  | "pending_review";

export interface MediaFile {
  id: string;
  url: string;
  type: string;
  isGenerated: boolean;
}

export interface Post {
  id: string;
  channelId: string;
  content: string;
  status: PostStatus;
  generationType: string;
  scheduledAt: string | null;
  publishedAt: string | null;
  telegramMessageId: string | null;
  errorMessage: string | null;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
  mediaFiles: MediaFile[];
}

// Simplified post type for list views
export interface PostListItem {
  id: string;
  content: string;
  status: string;
  generationType: string;
  scheduledAt: string | null;
  publishedAt: string | null;
  createdAt: string;
  mediaFiles?: MediaFile[];
}

// === Content Source Types ===

export interface ContentSource {
  id: string;
  telegramUsername: string;
  isActive: boolean;
  lastScrapedAt: string | null;
  _count: {
    scrapedContent: number;
  };
}

export interface ScrapedContent {
  id: string;
  telegramMessageId: string;
  text: string | null;
  mediaUrls: string[];
  views: number;
  forwards: number;
  reactions: number;
  scrapedAt: string;
  usedForGeneration: boolean;
}

export interface ContentResponse<T> {
  data: T[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}

// === Generation Types ===

export interface SourceMedia {
  url: string;
  type: string;
}

export interface SourceContent {
  id: string;
  text: string | null;
  telegramLink: string;
  media: SourceMedia[];
}

export interface ImageAnalysisResult {
  hasWatermark: boolean;
  hasLink: boolean;
  hasLogo: boolean;
  reasoning: string;
  suggestedPrompt?: string;
}

export interface PostImage {
  url: string;
  isGenerated: boolean;
  sourceId?: string;
  prompt?: string;
  analysisResult?: ImageAnalysisResult;
  originalUrl?: string;
  svgUrl?: string;
  isSvg?: boolean;
  /** Storage path of the source image used to generate this image (for SVG regeneration) */
  sourceStoragePath?: string;
}

export type ImageStrategy = "none" | "use_original" | "generate_new";

export interface ImageDecision {
  strategy: ImageStrategy;
  originalImageSourceIds?: string[];
  imagePrompts?: string[];
  reasoning?: string;
}

export interface GeneratedPost {
  content: string;
  angle: string;
  sourceIds: string[];
  imageDecision?: ImageDecision;
  images?: PostImage[];
}

// === API Response Types ===

export interface ApiResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
}
