import { useState } from "react";
import { useRouter } from "next/router";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import {
  Send,
  RotateCcw,
  ExternalLink,
  Trash2,
  Edit2,
  Clock,
  CheckCircle,
  AlertCircle,
  Loader2,
} from "lucide-react";
import { useAuth, useRequireAuth } from "~/hooks/useAuth";
import { AppHeader, PageHeader } from "~/components/layout/header";
import { PageLayout } from "~/components/layout/page-layout";
import { Button } from "~/components/ui/button";
import { Spinner } from "~/components/ui/spinner";
import { ConfirmModal } from "~/components/ui/confirm-modal";
import { PostEditorModal } from "~/components/posts/post-editor-modal";
import { ContentDetailCard } from "~/components/content/content-detail-card";
import { PostMetrics } from "~/components/content/content-metrics";
import { type ChipProps } from "~/components/content/content-list-item";
import { useI18n } from "~/i18n";

interface Channel {
  id: string;
  title: string;
  username: string | null;
}

interface Post {
  id: string;
  channelId: string;
  content: string;
  status: string;
  generationType: string;
  scheduledAt: string | null;
  publishedAt: string | null;
  telegramMessageId: string | null;
  errorMessage: string | null;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

type PostStatus = "draft" | "scheduled" | "publishing" | "published" | "failed" | "pending_review";

const statusConfig: Record<PostStatus, { variant: ChipProps["variant"]; icon: React.ReactNode }> = {
  draft: { variant: "default", icon: null },
  scheduled: { variant: "info", icon: <Clock className="h-3 w-3" /> },
  publishing: { variant: "warning", icon: <Loader2 className="h-3 w-3 animate-spin" /> },
  published: { variant: "success", icon: <CheckCircle className="h-3 w-3" /> },
  failed: { variant: "error", icon: <AlertCircle className="h-3 w-3" /> },
  pending_review: { variant: "info", icon: <Send className="h-3 w-3" /> },
};

export default function PostDetailPage() {
  const router = useRouter();
  const { id: channelId, postId } = router.query;
  const queryClient = useQueryClient();
  const { isLoading: authLoading } = useRequireAuth();
  const { user, logout } = useAuth();
  const { t } = useI18n();

  const [deleteConfirmOpen, setDeleteConfirmOpen] = useState(false);
  const [editModalOpen, setEditModalOpen] = useState(false);
  const [editContent, setEditContent] = useState("");

  const { data: channel, isLoading: channelLoading } = useQuery({
    queryKey: ["channel", channelId],
    queryFn: async () => {
      const res = await fetch(`/api/channels/${channelId}`);
      const json = await res.json();
      return json.data as Channel;
    },
    enabled: !!channelId && !authLoading,
  });

  const { data: post, isLoading: postLoading } = useQuery({
    queryKey: ["post", postId],
    queryFn: async () => {
      const res = await fetch(`/api/posts/${postId}`);
      const json = await res.json();
      return json.data as Post;
    },
    enabled: !!postId && !authLoading,
  });

  const publishMutation = useMutation({
    mutationFn: async () => {
      const res = await fetch(`/api/posts/${postId}/publish`, {
        method: "POST",
      });
      const data = await res.json();
      if (!data.success) throw new Error(data.error);
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["post", postId] });
      queryClient.invalidateQueries({ queryKey: ["posts", channelId] });
    },
  });

  const updateMutation = useMutation({
    mutationFn: async (content: string) => {
      const res = await fetch(`/api/posts/${postId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ content }),
      });
      const data = await res.json();
      if (!data.success) throw new Error(data.error);
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["post", postId] });
      queryClient.invalidateQueries({ queryKey: ["posts", channelId] });
      setEditModalOpen(false);
    },
  });

  const deleteMutation = useMutation({
    mutationFn: async () => {
      const res = await fetch(`/api/posts/${postId}`, {
        method: "DELETE",
      });
      const data = await res.json();
      if (!data.success) throw new Error(data.error);
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["posts", channelId] });
      router.push(`/channels/${channelId}`);
    },
  });

  const handleEditClick = () => {
    if (post) {
      setEditContent(post.content);
      setEditModalOpen(true);
    }
  };

  const getStatusLabel = (status: PostStatus): string => {
    switch (status) {
      case "draft":
        return t("posts.status.draft");
      case "scheduled":
        return t("posts.status.scheduled");
      case "publishing":
        return t("posts.status.publishing");
      case "published":
        return t("posts.status.published");
      case "failed":
        return t("posts.status.failed");
      case "pending_review":
        return t("posts.status.pending_review");
      default:
        return t("posts.status.draft");
    }
  };

  const isLoading = authLoading || channelLoading || postLoading;

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[var(--bg-secondary)]">
        <Spinner size="lg" />
      </div>
    );
  }

  if (!channel || !post) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[var(--bg-secondary)]">
        <p className="text-[var(--text-secondary)]">{t("common.notFound")}</p>
      </div>
    );
  }

  const canEdit = ["draft", "failed"].includes(post.status);
  const canPublish = post.status === "draft";
  const canRetry = post.status === "failed";
  const canDelete = post.status === "draft";

  const telegramUrl =
    post.status === "published" && post.telegramMessageId && channel.username
      ? `https://t.me/${channel.username}/${post.telegramMessageId}`
      : null;

  const status = post.status as PostStatus;
  const config = statusConfig[status] || statusConfig.draft;

  const chips: ChipProps[] = [
    {
      label: getStatusLabel(status),
      icon: config.icon,
      variant: config.variant,
    },
  ];

  return (
    <PageLayout title={`${t("posts.postDetail")} - ${channel.title}`}>
      <AppHeader user={user} onLogout={logout} />

      <div className="px-4 md:px-6 lg:px-8 py-6 max-w-3xl mx-auto">
        <PageHeader
          title={t("posts.postDetail")}
          breadcrumbs={[
            { label: t("common.home"), href: "/" },
            { label: t("nav.channels"), href: "/channels" },
            { label: channel.title, href: `/channels/${channelId}` },
            { label: t("posts.postDetail") },
          ]}
          actions={
            <div className="flex items-center gap-2">
              {canEdit && (
                <Button variant="secondary" size="sm" onClick={handleEditClick}>
                  <Edit2 className="h-4 w-4" />
                  {t("common.edit")}
                </Button>
              )}
              {canPublish && (
                <Button
                  size="sm"
                  onClick={() => publishMutation.mutate()}
                  disabled={publishMutation.isPending}
                >
                  <Send className="h-4 w-4" />
                  {t("posts.publish")}
                </Button>
              )}
              {canRetry && (
                <Button
                  size="sm"
                  variant="secondary"
                  onClick={() => publishMutation.mutate()}
                  disabled={publishMutation.isPending}
                >
                  <RotateCcw className="h-4 w-4" />
                  {t("common.retry")}
                </Button>
              )}
              {telegramUrl && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => window.open(telegramUrl, "_blank")}
                >
                  <ExternalLink className="h-4 w-4" />
                  {t("posts.openInTelegram")}
                </Button>
              )}
              {canDelete && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => setDeleteConfirmOpen(true)}
                >
                  <Trash2 className="h-4 w-4" />
                  {t("common.delete")}
                </Button>
              )}
            </div>
          }
        />

        <ContentDetailCard
          text={post.content}
          chips={chips}
          metrics={
            <PostMetrics
              createdAt={post.createdAt}
              publishedAt={post.publishedAt}
              scheduledAt={post.scheduledAt}
            />
          }
          date={post.createdAt}
          errorMessage={post.errorMessage}
        />
      </div>

      <PostEditorModal
        open={editModalOpen}
        onOpenChange={setEditModalOpen}
        content={editContent}
        onContentChange={setEditContent}
        onSave={() => updateMutation.mutate(editContent)}
        onCancel={() => setEditModalOpen(false)}
        isSaving={updateMutation.isPending}
        channelName={channel.title}
        isGenerated={false}
      />

      <ConfirmModal
        open={deleteConfirmOpen}
        onOpenChange={setDeleteConfirmOpen}
        title={t("posts.deleteConfirmTitle")}
        description={t("posts.deleteConfirmDescription")}
        confirmLabel={t("common.delete")}
        onConfirm={() => deleteMutation.mutate()}
        isLoading={deleteMutation.isPending}
        variant="danger"
      />
    </PageLayout>
  );
}
