// Data transformers for converting database models to API responses

// BigInt serialization helper
function serializeBigInt(value: bigint): string {
  return value.toString();
}

// Input types for transformers (matching Prisma output)
interface ChannelInput {
  id: string;
  telegramId: bigint;
  username: string | null;
  title: string;
  niche: string | null;
  tone: string;
  language: string;
  hashtags: string[];
  createdAt: Date;
  updatedAt: Date;
}

interface MediaFileInput {
  id: string;
  url: string;
  type: string;
  isGenerated: boolean;
}

interface PostInput {
  id: string;
  channelId: string;
  content: string;
  status: string;
  generationType: string;
  scheduledAt: Date | null;
  publishedAt: Date | null;
  telegramMessageId: bigint | null;
  errorMessage: string | null;
  isAutoGenerated: boolean;
  createdAt: Date;
  updatedAt: Date;
  mediaFiles?: MediaFileInput[];
}

/**
 * Transform a Channel to API response format.
 */
export function transformChannel(channel: ChannelInput) {
  return {
    id: channel.id,
    telegramId: serializeBigInt(channel.telegramId),
    username: channel.username,
    title: channel.title,
    niche: channel.niche,
    tone: channel.tone,
    language: channel.language,
    hashtags: channel.hashtags,
    createdAt: channel.createdAt.toISOString(),
    updatedAt: channel.updatedAt.toISOString(),
  };
}

/**
 * Transform a Post to API response format.
 */
export function transformPost(post: PostInput) {
  return {
    id: post.id,
    channelId: post.channelId,
    content: post.content,
    status: post.status,
    generationType: post.generationType,
    scheduledAt: post.scheduledAt?.toISOString() ?? null,
    publishedAt: post.publishedAt?.toISOString() ?? null,
    telegramMessageId: post.telegramMessageId
      ? serializeBigInt(post.telegramMessageId)
      : null,
    errorMessage: post.errorMessage,
    isAutoGenerated: post.isAutoGenerated,
    createdAt: post.createdAt.toISOString(),
    updatedAt: post.updatedAt.toISOString(),
    mediaFiles: post.mediaFiles?.map((mf) => ({
      id: mf.id,
      url: mf.url,
      type: mf.type,
      isGenerated: mf.isGenerated,
    })),
  };
}

/**
 * Transform a ContentSource to API response format.
 */
export function transformContentSource(source: {
  id: string;
  telegramUsername: string;
  isActive: boolean;
  lastScrapedAt: Date | null;
  _count?: { scrapedContent: number };
}) {
  return {
    id: source.id,
    telegramUsername: source.telegramUsername,
    isActive: source.isActive,
    lastScrapedAt: source.lastScrapedAt?.toISOString() ?? null,
    _count: source._count,
  };
}

/**
 * Transform a ScrapedContent to API response format.
 */
export function transformScrapedContent(content: {
  id: string;
  telegramMessageId: bigint;
  text: string | null;
  mediaUrls: string[];
  views: number;
  forwards: number;
  reactions: number;
  scrapedAt: Date;
  usedForGeneration: boolean;
}) {
  return {
    id: content.id,
    telegramMessageId: serializeBigInt(content.telegramMessageId),
    text: content.text,
    mediaUrls: content.mediaUrls,
    views: content.views,
    forwards: content.forwards,
    reactions: content.reactions,
    scrapedAt: content.scrapedAt.toISOString(),
    usedForGeneration: content.usedForGeneration,
  };
}

/**
 * Create pagination response metadata.
 */
export function createPagination(page: number, limit: number, total: number) {
  return {
    page,
    limit,
    total,
    totalPages: Math.ceil(total / limit),
  };
}
